x-networks: &networks
  networks:
    - nuk-network

services:
  api:
    image: hub.duonglt.net/nuk:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nuk-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - mailpit
    <<: *networks
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16-alpine
    container_name: nuk-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nuk
      TZ: UTC
    volumes:
      - postgres:/var/lib/postgresql/data
    <<: *networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: nuk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    <<: *networks
    volumes:
      - redis:/data

  mailpit:
    image: axllent/mailpit
    container_name: nuk-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    <<: *networks

networks:
  nuk-network:
    driver: bridge

volumes:
  redis:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/redis
      o: bind
  postgres:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/postgres
      o: bind

