FROM golang:1.24-alpine

# Set environment variables for development
ENV CGO_ENABLED=1 \
    GO111MODULE=on \
    GOOS=linux

WORKDIR /app

# Install necessary build dependencies
RUN apk add --no-cache gcc musl-dev git curl make && \
    go install github.com/air-verse/air@latest

# Copy go.mod and go.sum files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Generate wire code
RUN go run github.com/google/wire/cmd/wire@latest gen ./internal

# Expose the application port
EXPOSE 8080

# Use air for hot reloading in development
CMD ["air", "-c", ".air.toml"]